version: '3.5'

services:
  postgres:
    container_name: epc_db_postgres
    image: postgres:12.6
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - epc
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tac62/epc:${NODE_BUILD}
    container_name: epc_app
    restart: always
    env_file: .env
    depends_on:
      - postgres
    environment:
      PORT: ${PORT}
      DATABASE_HOST: postgres
    ports:
      - '${PORT}:${PORT}'
    networks:
      - epc

networks:
  epc:
    driver: "bridge"
